static const char* FIRMWARE_VERSION = "v13-ui-ota";

void setupWebUI() {
  WiFi.mode(WIFI_STA); WiFi.setAutoReconnect(true); WiFi.begin(WIFI_SSID,WIFI_PASS); addLog(String("[WIFI] connecting to ")+WIFI_SSID);
  uint32_t start=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-start<12000)delay(100);
  if(WiFi.status()==WL_CONNECTED){addLog(String("[WIFI] connected IP=")+WiFi.localIP().toString());if(MDNS.begin(MDNS_NAME))addLog("[WIFI] mDNS http://t1n-lock.local/");}else addLog("[WIFI] initial connect timed out; reconnect will continue");
  webServer.on("/",HTTP_GET,[](){webServer.sendHeader("Cache-Control","no-store");webServer.send_P(200,"text/html; charset=utf-8",MAIN_HTML);});webServer.on("/debug",HTTP_GET,[](){webServer.sendHeader("Cache-Control","no-store");webServer.send_P(200,"text/html; charset=utf-8",DASHBOARD_HTML);});webServer.on("/manifest.webmanifest",HTTP_GET,[](){webServer.send_P(200,"application/manifest+json; charset=utf-8",MANIFEST_JSON);});webServer.on("/icon.svg",HTTP_GET,[](){webServer.send_P(200,"image/svg+xml",ICON_SVG);});webServer.on("/update",HTTP_GET,[](){webServer.sendHeader("Cache-Control","no-store");webServer.send_P(200,"text/html; charset=utf-8",OTA_HTML);});

  webServer.on("/api/update",HTTP_POST,[](){bool ok=!Update.hasError();webServer.sendHeader("Connection","close");webServer.send(ok?200:500,"text/plain",ok?"Firmware installed successfully. Rebooting now...":String("Firmware update failed. Error code: ")+Update.getError());if(ok){addLog("[OTA] update complete; rebooting");delay(700);ESP.restart();}},[](){HTTPUpload& upload=webServer.upload();if(upload.status==UPLOAD_FILE_START){addLog(String("[OTA] upload start: ")+upload.filename);gpio23Forced=false;gpio23ForceUntil=0;setLockOutput(false,"ota");if(!upload.filename.endsWith(".bin")){Update.abort();return;}if(!Update.begin(UPDATE_SIZE_UNKNOWN,U_FLASH))addLog(String("[OTA] Update.begin failed: ")+Update.errorString());}else if(upload.status==UPLOAD_FILE_WRITE){if(!Update.hasError()){size_t w=Update.write(upload.buf,upload.currentSize);if(w!=upload.currentSize)addLog(String("[OTA] flash write failed: ")+Update.errorString());}}else if(upload.status==UPLOAD_FILE_END){if(Update.end(true))addLog(String("[OTA] flash complete bytes=")+upload.totalSize);else addLog(String("[OTA] Update.end failed: ")+Update.errorString());}else if(upload.status==UPLOAD_FILE_ABORTED){Update.abort();addLog("[OTA] upload aborted");}});

  webServer.on("/api/latest-version",HTTP_GET,[](){String v,u,s,r;if(!fetchLatestManifest(v,u,s,r)){webServer.send(502,"application/json",String("{\"error\":")+jsonQuote(r)+"}");return;}webServer.send(200,"application/json",String("{\"version\":")+jsonQuote(v)+",\"firmware_url\":"+jsonQuote(u)+"}");});
  webServer.on("/api/update-latest",HTTP_POST,[](){String v,u,s,r;addLog("[REMOTE OTA] fetching latest manifest");if(!fetchLatestManifest(v,u,s,r)){webServer.send(502,"text/plain",String("Manifest failed: ")+r);return;}addLog(String("[REMOTE OTA] manifest version=")+v);bool ok=installFirmwareFromUrl(u,s,r);webServer.sendHeader("Connection","close");webServer.send(ok?200:500,"text/plain",ok?String("Installed ")+v+". "+r:r);if(ok){delay(900);ESP.restart();}});
  // Retain direct URL endpoint for diagnostics/manual testing.
  webServer.on("/api/update-url",HTTP_POST,[](){String url=webServer.arg("url"),sha=webServer.arg("sha256");url.trim();sha.trim();if(url.length()==0){webServer.send(400,"text/plain","Missing firmware URL");return;}String r;bool ok=installFirmwareFromUrl(url,sha,r);webServer.sendHeader("Connection","close");webServer.send(ok?200:500,"text/plain",r);if(ok){delay(900);ESP.restart();}});

  webServer.on("/api/status",HTTP_GET,[](){int bonds=esp_ble_get_bond_device_num();uint32_t age=phoneSeen?(millis()-lastSeenMs):0;String auth=hasIRK?"PAIRED / IRK READY":(bleAuthCount?String("FAILED ")+bleAuthFailReason:"PAIRING REQUIRED");String j="{";
    j+="\"firmware\":"+jsonQuote(FIRMWARE_VERSION)+",";j+="\"lockState\":"+jsonQuote(lockStateName())+",";j+="\"cmd\":"+jsonQuote(lastCommand)+",";j+="\"result\":"+jsonQuote(lastCommandResult)+",";j+="\"drvClass\":"+jsonQuote(ledClassName(drvLed.cls))+",";j+="\"paxClass\":"+jsonQuote(ledClassName(paxLed.cls))+",";j+="\"g21\":"+jsonQuote(digitalRead(PIN_DRV_LED)?"HIGH":"LOW")+",";j+="\"g18\":"+jsonQuote(digitalRead(PIN_PAX_LED)?"HIGH":"LOW")+",";j+="\"g19\":"+jsonQuote(digitalRead(PIN_CTM_SENSE)?"HIGH":"LOW")+",";j+="\"g23\":"+jsonQuote(digitalRead(PIN_LOCK_PULSE)?"HIGH":"LOW")+",";j+="\"pulses\":"+jsonQuote(String(pulseCountTotal))+",";j+="\"ctmEdges\":"+jsonQuote(String(ctmLast5sEdges))+",";j+="\"ctmTotal\":"+jsonQuote(String(ctmEdgeTotal))+",";j+="\"ctmDiag\":"+jsonQuote(ctmDiagnosticName())+",";j+="\"bleMode\":"+jsonQuote(bleMode)+",";j+="\"gatt\":"+jsonQuote(boolText(bleGattConnected))+",";j+="\"auth\":"+jsonQuote(auth)+",";j+="\"bonds\":"+jsonQuote(String(bonds))+",";j+="\"irk\":"+jsonQuote(boolText(hasIRK))+",";j+="\"irkfp\":"+jsonQuote(irkShort())+",";j+="\"phone\":"+jsonQuote(boolText(phoneSeen))+",";j+="\"rssi\":"+jsonQuote(String(lastRSSI)+" dBm")+",";j+="\"age\":"+jsonQuote(phoneSeen?String(age/1000.0,1)+" s":"--")+",";j+="\"strong\":"+jsonQuote(String(strongCount))+",";j+="\"scans\":"+jsonQuote(String(bleScanCycles))+",";j+="\"adverts\":"+jsonQuote(String(bleAdvertCount))+",";j+="\"rpas\":"+jsonQuote(String(bleRpaCount))+",";j+="\"matches\":"+jsonQuote(String(bleMatchCount))+",";j+="\"bleEvent\":"+jsonQuote(lastBleEvent)+",";j+="\"bleAddr\":"+jsonQuote(lastBleAddress)+",";j+="\"auto\":"+jsonQuote(hasIRK?"ALWAYS ON":"WAITING FOR PAIRING")+",";j+="\"prox\":"+jsonQuote(proximityUnlocked?"NEAR/UNLOCKED CYCLE":"AWAY/IDLE")+",";j+="\"trend\":"+jsonQuote(trendStatus)+",";j+="\"weakAge\":"+jsonQuote(weakRssiSinceMs?String((millis()-weakRssiSinceMs)/1000.0,1)+" s":"--")+",";j+="\"wifi\":"+jsonQuote(WiFi.status()==WL_CONNECTED?WiFi.localIP().toString():"DISCONNECTED")+",";j+="\"uptime\":"+jsonQuote(String(millis()/1000)+" s")+",";j+="\"heap\":"+jsonQuote(String(ESP.getFreeHeap())+" bytes")+",";j+="\"unlockThreshold\":"+String(rssiUnlockThreshold)+",";j+="\"lockThreshold\":"+String(rssiLockThreshold)+",";j+="\"goneTimeout\":"+String(phoneGoneTimeoutMs/1000)+"}";webServer.send(200,"application/json",j);});

  webServer.on("/api/log",HTTP_GET,[](){String out;for(int n=0;n<eventLogCount;n++){int idx=(eventLogHead-eventLogCount+n+LOG_LINES)%LOG_LINES;out+=eventLog[idx]+"\n";}webServer.send(200,"text/plain",out);});
  webServer.on("/api/settings",HTTP_POST,[](){if(webServer.hasArg("unlock"))rssiUnlockThreshold=constrain(webServer.arg("unlock").toInt(),-100,-40);if(webServer.hasArg("lock"))rssiLockThreshold=constrain(webServer.arg("lock").toInt(),-110,-50);if(webServer.hasArg("timeout")){uint32_t sec=(uint32_t)constrain(webServer.arg("timeout").toInt(),3,120);phoneGoneTimeoutMs=sec*1000UL;weakRssiTimeoutMs=sec*1000UL;}EEPROM.writeInt(ADDR_UNLOCK_RSSI,rssiUnlockThreshold);EEPROM.writeInt(ADDR_LOCK_RSSI,rssiLockThreshold);EEPROM.writeUInt(ADDR_TIMEOUT_SEC,phoneGoneTimeoutMs/1000UL);EEPROM.writeByte(ADDR_SETTINGS_VERSION,SETTINGS_VERSION);EEPROM.commit();webServer.send(200,"text/plain","OK");});
  webServer.on("/api/cmd",HTTP_POST,[](){String c=webServer.arg("do");if(c=="lock")ensureDesiredState(true,true);else if(c=="unlock")ensureDesiredState(false,true);else if(c=="pulse1")directPulse();else if(c=="pulse2")directTwoPulses();else if(c=="gpioOn"){gpio23Forced=true;gpio23ForceUntil=millis()+8000;setLockOutput(true,"web-force");}else if(c=="gpioOff"){gpio23Forced=false;gpio23ForceUntil=0;setLockOutput(false,"web-force-off");}else if(c=="simApproach")ensureDesiredState(false,false);else if(c=="simDepart")ensureDesiredState(true,false);else if(c=="recoverIrk"){bool ok=recoverIRKFromFirstBond();if(ok){webServer.send(200,"text/plain","IRK recovered; rebooting");delay(500);ESP.restart();return;}}else if(c=="clearBle"){removeAllBonds();clearIRK();webServer.send(200,"text/plain","cleared; rebooting");delay(700);ESP.restart();return;}else if(c=="reboot"){webServer.send(200,"text/plain","rebooting");delay(300);ESP.restart();return;}else if(c=="clearLog"){clearEventLog();addLog("[LOG] cleared");}else{webServer.send(400,"text/plain","unknown command");return;}webServer.send(200,"text/plain","OK");});
  webServer.begin();addLog("[WEB] dashboard started");
}

uint32_t lastWifiReconnect=0;void updateWebUI(){webServer.handleClient();if(WiFi.status()!=WL_CONNECTED&&millis()-lastWifiReconnect>30000){lastWifiReconnect=millis();WiFi.disconnect();WiFi.begin(WIFI_SSID,WIFI_PASS);}}
void setup(){Serial.begin(115200);delay(300);pinMode(PIN_LOCK_PULSE,OUTPUT);digitalWrite(PIN_LOCK_PULSE,LOW);pinMode(PIN_STATUS_LED,OUTPUT);digitalWrite(PIN_STATUS_LED,LOW);pinMode(PIN_CTM_SENSE,INPUT_PULLUP);pinMode(PIN_DRV_LED,INPUT_PULLUP);pinMode(PIN_PAX_LED,INPUT_PULLUP);attachInterrupt(digitalPinToInterrupt(PIN_CTM_SENSE),onCtmEdge,CHANGE);ctmWindowStart=millis();EEPROM.begin(EEPROM_SIZE);hasIRK=loadIRK();int8_t savedLock=EEPROM.readChar(ADDR_LAST_LOCK);if(savedLock==VEH_LOCKED||savedLock==VEH_UNLOCKED)lastKnownLockState=(VehicleLockState)savedLock;
 if(EEPROM.readByte(ADDR_SETTINGS_VERSION)==SETTINGS_VERSION){int u=EEPROM.readInt(ADDR_UNLOCK_RSSI),l=EEPROM.readInt(ADDR_LOCK_RSSI);uint32_t t=EEPROM.readUInt(ADDR_TIMEOUT_SEC);if(u>=-100&&u<=-40)rssiUnlockThreshold=u;if(l>=-110&&l<=-50)rssiLockThreshold=l;if(t>=3&&t<=120){phoneGoneTimeoutMs=t*1000UL;weakRssiTimeoutMs=phoneGoneTimeoutMs;}}else{rssiUnlockThreshold=-80;rssiLockThreshold=-95;phoneGoneTimeoutMs=10000;weakRssiTimeoutMs=10000;EEPROM.writeInt(ADDR_UNLOCK_RSSI,rssiUnlockThreshold);EEPROM.writeInt(ADDR_LOCK_RSSI,rssiLockThreshold);EEPROM.writeUInt(ADDR_TIMEOUT_SEC,10);EEPROM.writeByte(ADDR_SETTINGS_VERSION,SETTINGS_VERSION);EEPROM.commit();}
 addLog(String("=== T1N Smart Lock ")+FIRMWARE_VERSION+" ===");addLog("[BUILD] Minimal SPIFFS / OTA");addLog(String("[STATE] boot remembered=")+rememberedLockName()+" unlock="+rssiUnlockThreshold+" lock="+rssiLockThreshold+" timeout="+(phoneGoneTimeoutMs/1000)+"s");setupWebUI();if(hasIRK)startScanMode();else startPairingMode();}
void loop(){updateWebUI();updateLedClassifiers();detectDoorCloseTransitions();updateCtmDiagnostics();updateRememberedLockFromLed();if(gpio23Forced&&(int32_t)(millis()-gpio23ForceUntil)>=0){gpio23Forced=false;gpio23ForceUntil=0;setLockOutput(false,"force-timeout");}if(hasIRK){updateBleScanning();updateProximityLogic();}delay(5);}
