#pragma once

const char MAIN_HTML[] PROGMEM = R"HTML(
<!doctype html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#101010"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="apple-mobile-web-app-title" content="T1N Lock"><link rel="manifest" href="/manifest.webmanifest"><link rel="apple-touch-icon" sizes="180x180" href="https://raw.githubusercontent.com/antflix/t1n_smartlock/main/assets/sprinter-smart-lock-180.png"><title>T1N Lock</title>
<style>*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{margin:0;min-height:100%;background:#101010;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display",system-ui,sans-serif}body{min-height:100dvh;padding:calc(env(safe-area-inset-top) + 12px) 14px calc(env(safe-area-inset-bottom) + 14px);display:flex;flex-direction:column;gap:12px}.status{display:flex;align-items:center;justify-content:center;gap:10px;min-height:54px;font-size:22px;font-weight:800}.dot{width:16px;height:16px;border-radius:50%;background:#777}.dot.locked{background:#45d483}.dot.unlocked{background:#ff6b6b}.dot.door{background:#ffd166}.controls{flex:1;display:grid;grid-template-rows:1fr 1fr;gap:14px;min-height:0}.big{border:0;border-radius:24px;color:#fff;font-weight:900;font-size:clamp(34px,10vw,58px);box-shadow:inset 0 1px rgba(255,255,255,.15),0 8px 28px rgba(0,0,0,.28)}.big:active{transform:scale(.985)}.lock{background:#b33f3f}.unlock{background:#2f7d49}.footer{display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:42px;color:#aaa;font-size:13px}.debug{position:fixed;right:10px;bottom:calc(env(safe-area-inset-bottom) + 8px);border:0;border-radius:12px;background:#29292c;color:#aaa;padding:9px 11px;font-size:12px;opacity:.82}.smallstate{padding-left:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:80%}</style></head><body>
<div class="status"><span id="dot" class="dot"></span><span id="state">CONNECTING...</span></div><div class="controls"><button class="big lock" onclick="sendCmd('lock')">LOCK</button><button class="big unlock" onclick="sendCmd('unlock')">UNLOCK</button></div><div class="footer"><span class="smallstate" id="detail">T1N Smart Lock</span></div><button class="debug" onclick="location.href='/debug'">DEBUG</button>
<script>const e=id=>document.getElementById(id);async function sendCmd(c){try{await fetch('/api/cmd?do='+c,{method:'POST'});}catch(x){}setTimeout(refresh,250)}function paint(s){const st=(s.lockState||'UNKNOWN').toUpperCase();e('state').textContent=st;e('dot').className='dot';if(st==='LOCKED')e('dot').classList.add('locked');else if(st==='UNLOCKED')e('dot').classList.add('unlocked');else if(st.includes('DOOR')||st.includes('BLINK'))e('dot').classList.add('door');e('detail').textContent='Auto '+s.auto+' | RSSI '+s.rssi}async function refresh(){try{paint(await(await fetch('/api/status',{cache:'no-store'})).json())}catch(x){e('state').textContent='OFFLINE';e('dot').className='dot'}}setInterval(refresh,700);refresh();</script></body></html>
)HTML";

const char MANIFEST_JSON[] PROGMEM = R"JSON({"name":"T1N Smart Lock","short_name":"T1N Lock","start_url":"/","scope":"/","display":"standalone","background_color":"#101010","theme_color":"#101010","icons":[{"src":"https://raw.githubusercontent.com/antflix/t1n_smartlock/main/assets/sprinter-smart-lock-180.png","sizes":"180x180","type":"image/png","purpose":"any"}]})JSON";

const char OTA_HTML[] PROGMEM = R"HTML(
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#101010"><title>T1N Firmware Update</title>
<style>*{box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display",system-ui,sans-serif;background:#101010;color:#fff;margin:0;padding:calc(env(safe-area-inset-top) + 16px) 20px calc(env(safe-area-inset-bottom) + 20px)}.wrap{max-width:620px;margin:auto}.nav{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px}.nav a{display:block;text-align:center;text-decoration:none;color:#fff;background:#2c2c2e;border-radius:12px;padding:12px;font-weight:750}.card{background:#1c1c1e;border-radius:18px;padding:20px;margin:16px 0}h1{font-size:26px;margin:4px 0 8px}h2{font-size:18px;margin:0 0 10px}.muted{color:#aaa;line-height:1.45}.version{font-size:17px;line-height:1.7}.version b{color:#8ec5ff}.btn{display:block;width:100%;border:0;border-radius:14px;padding:16px;font-size:17px;font-weight:800;background:#356aa0;color:#fff;margin-top:12px;text-align:center;text-decoration:none}.btn:disabled{opacity:.45}.secondary{background:#555}.status{margin-top:14px;white-space:pre-wrap;word-break:break-word;color:#ddd}.file{display:block;width:100%;margin-top:14px;padding:13px;border:1px solid #444;border-radius:12px;background:#121214;color:#ddd}</style></head><body><div class="wrap">
<div class="nav"><a href="/">MAIN</a><a href="/debug">DIAGNOSTICS</a></div><h1>Firmware Update</h1>
<div class="card"><h2>Version</h2><div class="version">Installed: <b id="installed">loading...</b><br>Latest: <b id="latestVersion">checking...</b></div></div>
<div class="card"><h2>Automatic update</h2><div class="muted">One click downloads the latest GitHub build through this phone, then uploads it directly to the ESP32 and reboots.</div><button id="latest" class="btn" onclick="installLatest()">INSTALL LATEST FIRMWARE</button><div id="status" class="status"></div></div>
<div class="card"><h2>Manual fallback</h2><div class="muted">Download the latest firmware file, choose it below, then upload it directly to the ESP32.</div><a class="btn secondary" href="https://github.com/antflix/t1n_smartlock/releases/download/latest/firmware.bin">DOWNLOAD LATEST .BIN</a><input id="binfile" class="file" type="file" accept=".bin,application/octet-stream"><button id="manual" class="btn secondary" onclick="installManual()">UPLOAD .BIN &amp; INSTALL</button><div id="manualStatus" class="status"></div></div>
</div><script>
const RELEASE_API='https://api.github.com/repos/antflix/t1n_smartlock/releases/tags/latest';
let cachedRelease=null;
async function getLatestRelease(){if(cachedRelease)return cachedRelease;const r=await fetch(RELEASE_API,{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error('GitHub release lookup failed: HTTP '+r.status);cachedRelease=await r.json();return cachedRelease;}
function getAsset(release,name){const a=(release.assets||[]).find(x=>x.name===name);if(!a)throw new Error(name+' was not found in the latest GitHub release');return a;}
async function fetchAsset(release,name){const a=getAsset(release,name);const r=await fetch(a.url,{cache:'no-store',headers:{Accept:'application/octet-stream'}});if(!r.ok)throw new Error('Could not download '+name+': HTTP '+r.status);return r;}
async function loadVersions(){try{const s=await(await fetch('/api/status',{cache:'no-store'})).json();document.getElementById('installed').textContent=s.firmware||'unknown';}catch(e){document.getElementById('installed').textContent='unknown';}try{const rel=await getLatestRelease();const mr=await fetchAsset(rel,'manifest.json');const m=await mr.json();document.getElementById('latestVersion').textContent=m.version||String(rel.target_commitish||'').slice(0,7)||'unknown';}catch(e){document.getElementById('latestVersion').textContent='unavailable';}}
async function uploadBufferToEsp32(buf,name,statusEl){const data=new FormData();data.append('firmware',new Blob([buf],{type:'application/octet-stream'}),name);statusEl.textContent='Uploading firmware to ESP32...';const r=await fetch('/api/update',{method:'POST',body:data});const t=await r.text();if(!r.ok)throw new Error(t||('ESP32 upload failed: HTTP '+r.status));return t;}
async function installLatest(){const b=document.getElementById('latest'),s=document.getElementById('status');b.disabled=true;try{s.textContent='Checking latest GitHub release...';const rel=await getLatestRelease();s.textContent='Downloading latest firmware through this phone...';const fr=await fetchAsset(rel,'firmware.bin');const buf=await fr.arrayBuffer();if(!buf.byteLength)throw new Error('Downloaded firmware file was empty');await uploadBufferToEsp32(buf,'firmware.bin',s);s.textContent='Installed. ESP32 is rebooting...';setTimeout(()=>location.href='/',5000);}catch(e){s.textContent='Update failed: '+(e&&e.message?e.message:e);b.disabled=false;}}
async function installManual(){const f=document.getElementById('binfile'),b=document.getElementById('manual'),s=document.getElementById('manualStatus');if(!f.files.length){s.textContent='Choose a .bin firmware file first.';return;}const file=f.files[0];if(!file.name.toLowerCase().endsWith('.bin')){s.textContent='The selected file must end in .bin';return;}b.disabled=true;try{const buf=await file.arrayBuffer();await uploadBufferToEsp32(buf,file.name,s);s.textContent='Installed. ESP32 is rebooting...';setTimeout(()=>location.href='/',5000);}catch(e){s.textContent='Update failed: '+(e&&e.message?e.message:e);b.disabled=false;}}
loadVersions();
</script></body></html>
)HTML";